### ISSUE TITLE
concurrentqueue doesn't seem to be bundled in the install target since version 1.0.0

### ISSUE THREAD

**Issue by mchagneux** [anira-project/anira#11]
Hi, 

I've pulled the repo and tried rebuilding the library to include it in my project, but the concurrentqueue dependency doesn't seem resolved by find_packag (the build works fine though).

Thanks in advance!

**Comment by faressc** [comment]
Can you provide us the CMake logs?

**Comment by mchagneux** [comment]
I get this in the configure step for a small test project where I just link anira to some executable:

```
[cmake] CMake Error at CMakeLists.txt:12 (find_package):
[cmake]   Found package configuration file:
[cmake] 
[cmake]     E:/audio_dev/tests/anira-1.0.0/lib/cmake/anira/aniraConfig.cmake
[cmake] 
[cmake]   but it set anira_FOUND to FALSE so package "anira" is considered to be NOT
[cmake]   FOUND.  Reason given by package:
[cmake] 
[cmake]   The following imported targets are referenced, but are missing:
[cmake]   concurrentqueue::concurrentqueue
[cmake] 
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

In my CMake I do this: 

````

list(APPEND CMAKE_PREFIX_PATH "${CMAKE_CURRENT_LIST_DIR}/anira-1.0.0")


find_package(anira REQUIRED)
target_include_directories(${TARGET_NAME} PUBLIC ${anira_INCLUDE_DIRS})


target_link_libraries(test_exec PRIVATE anira::anira)
```

**Comment by faressc** [comment]
Ok, we will have a look into this very soon. Which operating system, compiler and cmake version are you using?

**Comment by mchagneux** [comment]
No problem!
I'm on Windows 10, currently with MSVC (but I use Clang for Windows for some projects, anira has been working fine with both so far). I'm using the CMake that comes bundled with VS2022 Community (`cmake version 3.29.5-msvc4`). 
I'm build anira separately, calling cmake install and then moving the files into my project.

**Comment by faressc** [comment]
Hi there,
I just released a new version where the bug should be fixed.
Could you confirm that it works now?

**Comment by mchagneux** [comment]
It works! Thank you.

**Comment by faressc** [comment]
Great - thanks for reporting back!
