### ISSUE TITLE
100% CPU use even on NONE backend.

### ISSUE THREAD

**Issue by mchagneux** [anira-project/anira#4]
Hi, 

I've built the juce example plugin and tried different backends. My machine is not really new (i7-7820HQ) but I'm still a bit surprised by the CPU usage of the example plugin (practically 100% and the OS freezes after a few seconds of use). Surprisingly this is also the case for the NONE backend. Is this expected behaviour that the NONE backend also consumes CPU ? Just checking to see if I missed something or if it's just my machine that can't handle basic ML workloads on CPU. 

Mathis.

**Comment by faressc** [comment]
Hey,

thanks for reaching out again. No, this is not normal at all. The NONE should run fine on almost all systems.
Could you build and run the benchmarks? Especially the advanced-benchmark should give us some insight into the performance. Delete the build folder, configure cmake and rebuild:
```bash
cmake . -B build -DCMAKE_BUILD_TYPE=Release -DANIRA_WITH_BENCHMARK=ON -DANIRA_WITH_EXAMPLES=ON
cmake --build build --config Release
```

Then run the benchmark with:
```bash
ctest -R Benchmark.Advanced -VV --timeout 100000
```
You don't need to run the full benchmark, as that could take quite some time. The beginning should help us. Then it would be great if you could post the results here.

Cheers,
Fares

**Comment by mchagneux** [comment]
Here's the benchmark for GuitarLSTM with a buffer size of 2048. This is the side I was using when running the plugin in JUCE AudioPluginHost with ASIO drivers.

Run on (8 X 2904 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 256 KiB (x4)
  L3 Unified 8192 KiB (x1)

----------------------------------------------------------------------------------------------------------------------------------------
Model: GuitarLSTM-dynamic.pt | Backend: libtorch | Sample Rate: 44100 Hz | Buffer Size: 2048 = 46.4399 ms
----------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------------------------------------------------------
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  37.8 ms         2.50 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  38.7 ms         1.25 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  40.2 ms         1.56 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  40.2 ms        0.938 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  41.5 ms        0.312 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  42.0 ms        0.625 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  38.6 ms         1.56 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  39.7 ms        0.312 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  40.8 ms        0.625 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time                  40.0 ms        0.312 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time_mean             40.0 ms         1.00 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time_median           40.1 ms        0.781 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time_stddev           1.31 ms        0.719 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time_cv               3.27 %         71.87 %            10
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time_min              37.8 ms        0.312 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time_max              42.0 ms         2.50 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/0/iterations:50/repeats:10/manual_time_percentile       41.5 ms         1.56 ms           10

----------------------------------------------------------------------------------------------------------------------------------------
Model: GuitarLSTM-libtorch-dynamic.onnx | Backend: onnx | Sample Rate: 44100 Hz | Buffer Size: 2048 = 46.4399 ms
----------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------

ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  21.6 ms         1.56 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  21.6 ms        0.938 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  20.9 ms         3.12 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  21.2 ms         1.88 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  20.9 ms         1.56 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  21.2 ms         1.56 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  21.3 ms         1.56 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  21.5 ms        0.938 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  22.1 ms         1.25 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time                  20.3 ms         2.81 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time_mean             21.2 ms         1.72 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time_median           21.3 ms         1.56 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time_stddev          0.485 ms        0.725 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time_cv               2.28 %         42.21 %            10
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time_min              20.3 ms        0.938 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time_max              22.1 ms         3.12 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/1/iterations:50/repeats:10/manual_time_percentile       21.6 ms         2.81 ms           10

----------------------------------------------------------------------------------------------------------------------------------------
Model: GuitarLSTM-2048.tflite | Backend: tflite | Sample Rate: 44100 Hz | Buffer Size: 2048 = 46.4399 ms
----------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------

ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  38.6 ms        0.938 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  39.4 ms        0.312 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  35.7 ms         1.88 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  41.4 ms        0.000 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  38.4 ms         1.88 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  39.4 ms         2.19 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  42.0 ms         1.25 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  38.4 ms         3.44 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  39.7 ms         1.25 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time                  37.4 ms        0.938 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time_mean             39.0 ms         1.41 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time_median           39.0 ms         1.25 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time_stddev           1.82 ms        0.991 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time_cv               4.67 %         70.47 %            10
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time_min              35.7 ms        0.000 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time_max              42.0 ms         3.44 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/2/iterations:50/repeats:10/manual_time_percentile       41.4 ms         2.19 ms           10

----------------------------------------------------------------------------------------------------------------------------------------
Model: no_model | Backend: none | Sample Rate: 44100 Hz | Buffer Size: 2048 = 46.4399 ms
----------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------

ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.21 ms         1.25 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.18 ms         1.56 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.20 ms        0.625 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.18 ms         1.25 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.18 ms         1.56 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.19 ms         1.25 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.30 ms         2.19 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.27 ms         1.25 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.27 ms         1.56 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time                  1.19 ms        0.938 ms           50
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time_mean             1.22 ms         1.34 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time_median           1.19 ms         1.25 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time_stddev          0.045 ms        0.418 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time_cv               3.70 %         31.10 %            10
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time_min              1.18 ms        0.625 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time_max              1.30 ms         2.19 ms           10
ProcessBlockFixture/BM_ADVANCED/2048/0/3/iterations:50/repeats:10/manual_time_percentile       1.27 ms         1.56 ms           10
[       OK ] Benchmark.Advanced (134973 ms)
[----------] 1 test from Benchmark (134973 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (134977 ms total)
[  PASSED  ] 1 test.

**Comment by faressc** [comment]
Seems like with 2048 samples you should be able to run the plugin, espacially with onnx and the bypass engine. What buffer size did you try?

**Comment by mchagneux** [comment]
I was using a buffer size of 2048 with the ASIO driver. I think the problem I'm seeing isn't directly to audio processing. Windows 10 starts freezing once I open the juce-example-plugin and let it run for a few seconds, so it looks like the message thread is being blocked somehow, or some problem with a lock somewhere. I don't remember having this problem on Linux but I had to switch to Windows. Could it be related to the `ANIRA_WITH_SEMAPHORE` option set to ON ?

**Comment by mchagneux** [comment]
Ok, will try all this in the coming days!

**Comment by faressc** [comment]
Cool, thanks!

**Comment by mchagneux** [comment]
To clarify, there is not crash, just an overall lag of the OS once I start a plugin that involves anira. So this isn't really traceable through Debug. I'll try to profile the program with something like Perfetto, there might be some problem with the message thread on Windows for some reason.

**Comment by mchagneux** [comment]
Hi again, 

Curiously there doesn't seem to be any problem with the nn-inference-template plugin (which comes with anira 0.1.0 if I'm correct). I didn't have the time to investigate further. Will keep you updated if I find the source of the problem.

**Comment by faressc** [comment]
Hi there,
Thanks for checking - I am very curious to find out more! You might also try updating the anira version of the nn-inference-template and see if that causes the same crashes. Anyway, thanks for your debugging already. Unfortunately, I cannot help with debugging since I do not have a Windows system.

**Comment by mchagneux** [comment]
The problems seems to be directly related to the semaphore. I pulled the latest version the anira submodule in nn-inference-template, and the problem was still there, unless I set `ANIRA_WTH_SEMAPHORE` to `OFF`. In this latter case the CPU usage is very reasonable (sub 20%).

**Comment by faressc** [comment]
Do I understand it correctly, that the version anira v0.1.0 does not have the problem?

**Comment by mchagneux** [comment]
Yes, from what I've seen: 
- anira 0.1.2 with semaphores has the problem.
- anira 0.1.2 without semaphores doesn't have the problem.
- anira 0.1.0 doesn't have the problem.

**Comment by mchagneux** [comment]
I didn't test 0.1.0 with juce-plugin-example.

**Comment by mchagneux** [comment]
Actually the problem appears / disappears simply by swapping the `anira.dll` file from the different versions in the executable folder.

**Comment by faressc** [comment]
Ok, thank you! We will investigate this further in the next days and let you know when we think to have found a fix. In the meantime it might be best for you to use anira v0.1.2 with the `ANIRA_WITH_SEMAPHORE` set to `OFF`. Just for the record, anira v0.1.0 uses semaphores by default - so it must be the implementation of the option without semaphores that caused the bug in the semaphore version...

**Comment by vackva** [comment]
I just confirmed the issue reported by @mchagneux with the MSVC compiler and generator. I traced the bug to commit 30abde5.

**Comment by vackva** [comment]
I resolved the issue by reverting `timeForExit` to the original value of 1 millisecond in `InferenceThread.cpp`:

```cpp
void InferenceThread::run() {
    // std::chrono::microseconds timeForExit(500);
    std::chrono::milliseconds timeForExit(1);
    ...
}
```

It appears that using `std::chrono::microseconds` is causing issues when multiple threads are active. However, when limiting the number of threads to 5 (out of 24 available), `std::chrono::microseconds` worked without issues.

**Comment by mchagneux** [comment]
Great, thanks! Will check this out once it's merged into main.

**Comment by faressc** [comment]
Hi Mathis,
We have updated our entire thread synchronization and scheduling architecture with several improvements. Although we only have a timeForExit of 50 microseconds now, everything should run much smoother now.
It would be great if you could test this again. We have backported the changes to tag v0.1.2, so you can either try the juce-example-plugin with this tag or the latest main.
The nn-inference-template will be updated soon.
Thanks for reporting the issue and testing - this was truly helpful!
Cheers!

**Comment by faressc** [comment]
The nn-inference-template has now been updated as well. So I consider this issue solved. Feel free to reopen if you still encounter problems.

**Comment by mchagneux** [comment]
> Hi Mathis, We have updated our entire thread synchronization and scheduling architecture with several improvements. Although we only have a timeForExit of 50 microseconds now, everything should run much smoother now. It would be great if you could test this again. We have backported the changes to tag v0.1.2, so you can either try the juce-example-plugin with this tag or the latest main. The nn-inference-template will be updated soon. Thanks for reporting the issue and testing - this was truly helpful! Cheers!


Just tried it and it's working perfectly now, thanks for the fix!
